namespace AIStudio.Tools.ToolCallingSystem.ToolCallingImplementations;

internal sealed record WebSearchPageRetrievalResult(IReadOnlyList<WebSearchPageResult> Results, bool RetrievalTimedOut, WebSearchPageRetrievalStatistics ErrorStatistics);