namespace AIStudio.Tools;

public enum Components
{
    NONE = 0,
    
    GRAMMAR_SPELLING_ASSISTANT,
    ICON_FINDER_ASSISTANT,
    REWRITE_ASSISTANT,
    TRANSLATION_ASSISTANT,
    AGENDA_ASSISTANT,
    CODING_ASSISTANT,
    TEXT_SUMMARIZER_ASSISTANT,
    EMAIL_ASSISTANT,
    LEGAL_CHECK_ASSISTANT,
    SYNONYMS_ASSISTANT,
    MY_TASKS_ASSISTANT,
    JOB_POSTING_ASSISTANT,
    
    CHAT,
}