namespace AIStudio.Tools;

public enum Event
{
    NONE,
    
    // Common events:
    STATE_HAS_CHANGED,
    CONFIGURATION_CHANGED,
    COLOR_THEME_CHANGED,
    STARTUP_PLUGIN_SYSTEM,
    STARTUP_ENTERPRISE_ENVIRONMENT,
    PLUGINS_RELOADED,
    SHOW_ERROR,
    SHOW_WARNING,
    SHOW_SUCCESS,
    TAURI_EVENT_RECEIVED,
    
    // Update events:
    USER_SEARCH_FOR_UPDATE,
    UPDATE_AVAILABLE,
    INSTALL_UPDATE,
    
    // Chat events:
    HAS_CHAT_UNSAVED_CHANGES,
    RESET_CHAT_STATE,
    LOAD_CHAT,
    CHAT_STREAMING_DONE,
    
    // Workspace events:
    WORKSPACE_LOADED_CHAT_CHANGED,
    WORKSPACE_TOGGLE_OVERLAY,
    
    // RAG events:
    RAG_AUTO_DATA_SOURCES_SELECTED,
    
    // File attachment events:
    REGISTER_FILE_DROP_AREA,
    UNREGISTER_FILE_DROP_AREA,
    
    // Send events:
    SEND_TO_GRAMMAR_SPELLING_ASSISTANT,
    SEND_TO_ICON_FINDER_ASSISTANT,
    SEND_TO_REWRITE_ASSISTANT,
    SEND_TO_TRANSLATION_ASSISTANT,
    SEND_TO_AGENDA_ASSISTANT,
    SEND_TO_CODING_ASSISTANT,
    SEND_TO_TEXT_SUMMARIZER_ASSISTANT,
    SEND_TO_CHAT,
    SEND_TO_EMAIL_ASSISTANT,
    SEND_TO_LEGAL_CHECK_ASSISTANT,
    SEND_TO_SYNONYMS_ASSISTANT,
    SEND_TO_MY_TASKS_ASSISTANT,
    SEND_TO_JOB_POSTING_ASSISTANT,
    SEND_TO_DOCUMENT_ANALYSIS_ASSISTANT,
}