namespace AIStudio.Components.Pages;

public enum SendToAssistant
{
    NONE = 0,
    
    GRAMMAR_SPELLING_ASSISTANT,
    ICON_FINDER_ASSISTANT,
    REWRITE_ASSISTANT,
    TRANSLATION_ASSISTANT,
    AGENDA_ASSISTANT,
    CODING_ASSISTANT,
    TEXT_SUMMARIZER_ASSISTANT,
}