using AIStudio.Settings.DataModel;

namespace AIStudio.Dialogs;

public readonly record struct DataSourceERIV1UsernamePasswordExportDialogResult(DataSourceERIUsernamePasswordMode UsernamePasswordMode);