namespace AIStudio.Components.Settings;

public enum SettingsPanel
{
    NONE,
    
    // Pages
    PROVIDER_PANEL,
    EMBEDDINGS_PANEL,
    DATA_SOURCES_PANEL,
    PROFILES_PANEL,
    APP_PANEL,
    CHAT_PANEL,
    WORKSPACE_PANEL,
    
    // ASSISTANTS
    ASSISTANT_GRAMMAR_SPELLING_PANEL,
    ASSISTANT_ICON_FINDER_PANEL,
    ASSISTANT_REWRITE_PANEL,
    ASSISTANT_TRANSLATION_PANEL,
    ASSISTANT_AGENDA_PANEL,
    ASSISTANT_CODING_PANEL,
    ASSISTANT_TEXT_SUMMARIZER_PANEL,
    ASSISTANT_EMAIL_PANEL,
    ASSISTANT_LEGAL_CHECK_PANEL,
    ASSISTANT_SYNONYMS_PANEL,
    ASSISTANT_MY_TASKS_PANEL,
    ASSISTANT_JOB_POSTING_PANEL,
    ASSISTANT_ERI_SERVER_PANEL,
    ASSISTANT_BIAS_OF_THE_DAY_PANEL,
    
    // Agents
    AGENT_DATA_SOURCE_SELECTION_PANEL,
    AGENT_RETRIEVAL_CONTEXT_VALIDATION_PANEL,
    AGENT_CONTENT_CLEANER_PANEL,
}