namespace AIStudio.Components.Settings;

public enum SettingsPanel
{
    NONE,
    
    // Pages
    PROVIDER_PANEL,
    EMBEDDINGS_PANEL,
    DATA_SOURCES_PANEL,
    PROFILES_PANEL,
    APP_PANEL,
    CHAT_PANEL,
    WORKSPACE_PANEL,
    
    // Agents
    AGENT_DATA_SOURCE_SELECTION_PANEL,
    AGENT_RETRIEVAL_CONTEXT_VALIDATION_PANEL,
    AGENT_CONTENT_CLEANER_PANEL,
}