namespace AIStudio.Assistants.Builder;

public enum LuaResponseParseError
{
    NONE,
    MISSING_JSON_OBJECT,
    INVALID_JSON,
    EMPTY_JSON_OBJECT,
    UNSUPPORTED_SCHEMA_VERSION,
    MISSING_PLUGIN_METADATA,
    MISSING_ASSISTANT_METADATA,
    INCOMPLETE_PLUGIN_METADATA,
    INCOMPLETE_ASSISTANT_METADATA,
    MISSING_LUA,
    LUA_MISSING_ID,
}