name: Build and Release
on:
  push
    
jobs:
  build-dotnet:
    name: Build .NET
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
          dotnet-quality: 'ga'
          cache: true
          cache-dependency-path: 'app/MindWork AI Studio/packages.lock.json'
      
      - name: Build .NET project
        run: |
          cd "app/MindWork AI Studio"
          dotnet publish --configuration release --runtime win-arm64 --disable-build-servers --force --output ../../publish/dotnet
          
      - name: Upload .NET artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet
          path: publish/dotnet/mindworkAIStudio
          if-no-files-found: error
          retention-days: 1